apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # This binds the PVC to the specific PV we created above
  # volumeName: {{ include "three-tier-app.fullname" . }}-mongo-pv